repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
    -   id: flake8
        exclude: aces-dev
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.23.0
    hooks:
    -   id: yapf
        exclude: aces/config/reference/aces-dev
