version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  apt_packages:
    - graphviz
    - graphviz-dev

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
