name: Configuration Artifacts

on: [push, pull_request]

jobs:
  configuration-artifacts:
    name: ${{ matrix.os }} - Python ${{ matrix.python-version }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.13]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Environment Variables
        run: |
          echo "CI_PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV
          echo "CI_PACKAGE=opencolorio_config_aces" >> $GITHUB_ENV
          echo "CI_SHA=${{ github.sha }}" >> $GITHUB_ENV
        shell: bash
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          sudo apt-get --yes install graphviz graphviz-dev
      - name: Install uv
        run: |
          pip install uv
        shell: bash
      - name: Install Package Dependencies
        run: |
          uv sync --all-extras --no-dev
          uv run python -c "import imageio;imageio.plugins.freeimage.download()"
        shell: bash
      - name: ACES - Conversion Graph
        run: |
          uv run invoke build-aces-conversion-graph
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: aces-conversion-graph
          path: |
            build/aces/graph/
      - name: Generation - Config - Common Tests
        run: |
          uv run invoke build-config-common-tests
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: config-common-tests
          path: |
            build/config/common/tests/
      - name: Generation - Config - ACES Reference (Analytical)
        run: |
          uv run invoke build-config-reference-analytical
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: config-reference-analytical
          path: |
            build/config/aces/analytical/
      - name: Generation - Config - ACES Reference
        run: |
          uv run invoke build-config-reference
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: config-reference
          path: |
            build/config/aces/reference/
      - name: Generation - Config - ACES CG
        run: |
          uv run invoke build-config-cg
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: config-cg
          path: |
            build/config/aces/cg/
      - name: Generation - Config - ACES Studio
        run: |
          uv run invoke build-config-studio
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: config-studio
          path: |
            build/config/aces/studio/
